(part "G125-MH11605L1P"
    (packageRef "G125-MH11605L1P")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
        (port "3" (symbPinId 3) (portName "3") (portType INOUT))
        (port "4" (symbPinId 4) (portName "4") (portType INOUT))
        (port "5" (symbPinId 5) (portName "5") (portType INOUT))
        (port "6" (symbPinId 6) (portName "6") (portType INOUT))
        (port "7" (symbPinId 7) (portName "7") (portType INOUT))
        (port "8" (symbPinId 8) (portName "8") (portType INOUT))
        (port "9" (symbPinId 9) (portName "9") (portType INOUT))
        (port "10" (symbPinId 10) (portName "10") (portType INOUT))
        (port "11" (symbPinId 11) (portName "11") (portType INOUT))
        (port "12" (symbPinId 12) (portName "12") (portType INOUT))
        (port "13" (symbPinId 13) (portName "13") (portType INOUT))
        (port "14" (symbPinId 14) (portName "14") (portType INOUT))
        (port "15" (symbPinId 15) (portName "15") (portType INOUT))
        (port "16" (symbPinId 16) (portName "16") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "181")
    (property "Mouser_Part_Number" "855-G125-MH11605L1P")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Harwin/G125-MH11605L1P?qs=kxSDgj%2F7uumIzP69oO%252BoMQ%3D%3D")
    (property "Manufacturer_Name" "Harwin")
    (property "Manufacturer_Part_Number" "G125-MH11605L1P")
    (property "Description" "Gecko Latch: 8+8 Pos Plug DIL Right-Angle 3.2mm THT Connector Latch THT Hold-Down")
    (property "Datasheet_Link" "https://content.harwin.com/m/844b40397efd33c6/original/DRG-00172-Technical-Drawing-Datasheet-G125-MHXXX05L1P-pdf.pdf")
    (property "symbolName1" "G125-MH11605L1P")
)
